# Generated by Django 5.2.9 on 2026-04-28 13:24

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="attractions/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_image",
                    models.ImageField(blank=True, null=True, upload_to="city_images/"),
                ),
                ("city_name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("phone_or_email", models.CharField(max_length=128)),
                ("message", models.TextField()),
                ("subject", models.CharField(blank=True, default="", max_length=256)),
                ("source", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает ответа"),
                            ("answered", "Отвечено"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_image",
                    models.ImageField(blank=True, null=True, upload_to="country_images/"),
                ),
                ("country_name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuizLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=64)),
                (
                    "phone_or_telegram",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("answers", models.JSONField()),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuizProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=64, unique=True)),
                ("answers", models.JSONField(default=dict)),
                ("current_question_index", models.PositiveSmallIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("radio", "Один ответ"),
                            ("checkbox", "Несколько ответов"),
                            ("text", "Текст"),
                        ],
                        default="radio",
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("whatsapp", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("about_text", models.TextField(blank=True)),
                ("about_video_url", models.URLField(blank=True)),
                ("years_experience", models.PositiveSmallIntegerField(default=5)),
                ("tourists_count", models.PositiveIntegerField(default=1200)),
                ("routes_count", models.PositiveSmallIntegerField(default=40)),
                ("privacy_policy_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="TourCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="category_icons/"),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransferRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_point", models.CharField(max_length=128)),
                ("arrival_point", models.CharField(max_length=128)),
                ("distance_km", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="AttractionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="attraction_images/")),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="nomads_area_app.attraction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attraction",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attractions",
                to="nomads_area_app.city",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="nomads_area_app.country",
            ),
        ),
        migrations.CreateModel(
            name="QuizAnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="nomads_area_app.quizquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "tour_type",
                    models.CharField(
                        choices=[("group", "Групповой"), ("private", "Приватный")],
                        max_length=16,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("all_year", "Круглый год"),
                            ("warm", "Тёплый сезон"),
                            ("winter", "Зима"),
                        ],
                        default="all_year",
                        max_length=16,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Лёгкий"), (2, "Средний"), (3, "Сложный")],
                        default=2,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("KGS", "KGS"), ("USD", "USD")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "max_people",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                ("description", models.TextField()),
                ("included", models.TextField()),
                ("not_included", models.TextField(blank=True)),
                ("tripadvisor_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tours",
                        to="nomads_area_app.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tours",
                        to="nomads_area_app.country",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tours",
                        to="nomads_area_app.tourcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItineraryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="itinerary/"),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("altitude", models.CharField(blank=True, max_length=64)),
                ("walking_distance", models.CharField(blank=True, max_length=64)),
                ("driving_distance", models.CharField(blank=True, max_length=64)),
                ("accommodation", models.CharField(blank=True, max_length=128)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary",
                        to="nomads_area_app.tour",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="nomads_area_app.tour",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExtraService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="extra_services/"),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("price", models.PositiveIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "price_label",
                    models.CharField(default="за 1 день тура", max_length=64),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_services",
                        to="nomads_area_app.tour",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attraction",
            name="tours",
            field=models.ManyToManyField(blank=True, related_name="attractions", to="nomads_area_app.tour"),
        ),
        migrations.CreateModel(
            name="TourDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "available_spots",
                    models.PositiveSmallIntegerField(validators=[
                        django.core.validators.MinValueValidator(0),
                        django.core.validators.MaxValueValidator(10),
                    ]),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates",
                        to="nomads_area_app.tour",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_start_date", models.DateField(blank=True, null=True)),
                ("preferred_end_date", models.DateField(blank=True, null=True)),
                ("customer_name", models.CharField(max_length=128)),
                ("customer_contact", models.CharField(default="", max_length=128)),
                (
                    "people_details",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("adults", models.PositiveSmallIntegerField(default=1)),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("number_of_people", models.PositiveSmallIntegerField()),
                ("price_per_person", models.PositiveIntegerField()),
                ("total_price", models.PositiveIntegerField()),
                ("remainder_amount", models.PositiveIntegerField(default=0)),
                ("deposit_percent", models.PositiveSmallIntegerField(default=30)),
                ("deposit_amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждён"),
                            ("cancelled", "Отменён"),
                            ("rejected", "Отклонён"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="nomads_area_app.tour",
                    ),
                ),
                (
                    "tour_date",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nomads_area_app.tourdate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tour_images/")),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="nomads_area_app.tour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourPriceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_people", models.PositiveSmallIntegerField()),
                ("max_people", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("price_per_person", models.PositiveIntegerField()),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers",
                        to="nomads_area_app.tour",
                    ),
                ),
            ],
            options={
                "ordering": ["min_people"],
            },
        ),
        migrations.CreateModel(
            name="TourRoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=128)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_points",
                        to="nomads_area_app.tour",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sedan", "Седан"),
                            ("minivan", "Минивэн"),
                            ("minibus", "Миниавтобус"),
                        ],
                        max_length=16,
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("seats", models.PositiveSmallIntegerField()),
                ("bags", models.PositiveSmallIntegerField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="nomads_area_app.transferroute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("travel_date", models.DateField(blank=True, null=True)),
                (
                    "flight_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "customer_phone",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
                ),
                ("passengers", models.PositiveSmallIntegerField(default=1)),
                ("luggage_count", models.PositiveSmallIntegerField(default=0)),
                ("total_price", models.PositiveIntegerField()),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждён"),
                            ("cancelled", "Отменён"),
                            ("rejected", "Отклонён"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomads_area_app.vehicletype",
                    ),
                ),
            ],
        ),
    ]
