# Generated by Django 5.2.9 on 2026-06-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='tripadvisor_widget_code',
        ),
    ]
