# Generated by Django 5.2.9 on 2026-04-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomads_area_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=128)),
                ("position", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="country",
            name="hero_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="country",
            name="symbol_image",
            field=models.ImageField(blank=True, null=True, upload_to="country_symbols/"),
        ),
        migrations.AddField(
            model_name="tour",
            name="activity_tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
