# Generated by Django 5.2.9 on 2026-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomads_area_app", "0002_teammember_country_hero_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attraction",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["city_name"]},
        ),
        migrations.AlterModelOptions(
            name="contactrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["country_name"]},
        ),
        migrations.AlterModelOptions(
            name="tour",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tourcategory",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="transferroute",
            options={"ordering": ["departure_point", "arrival_point"]},
        ),
        migrations.AlterModelOptions(
            name="transportrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="vehicletype",
            options={"ordering": ["route_id", "category"]},
        ),
        migrations.AddIndex(
            model_name="attraction",
            index=models.Index(fields=["city", "is_active"], name="attraction_city_active_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status", "created_at"], name="booking_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["tour", "created_at"], name="booking_tour_created_idx"),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(fields=["status", "created_at"], name="contact_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(fields=["source", "created_at"], name="contact_source_created_idx"),
        ),
        migrations.AddIndex(
            model_name="quizprogress",
            index=models.Index(
                fields=["session_key", "is_completed"],
                name="quizprogress_session_done_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(fields=["is_active", "order"], name="quizq_active_order_idx"),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(fields=["tour_type", "is_active"], name="tour_type_active_idx"),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(fields=["country", "city"], name="tour_country_city_idx"),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(fields=["season", "difficulty"], name="tour_season_diff_idx"),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(fields=["price"], name="tour_price_idx"),
        ),
        migrations.AddIndex(
            model_name="tourdate",
            index=models.Index(
                fields=["start_date", "available_spots"],
                name="tourdate_start_spots_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transportrequest",
            index=models.Index(fields=["status", "created_at"], name="transport_status_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(fields=("country", "city_name"), name="unique_city_per_country"),
        ),
        migrations.AddConstraint(
            model_name="tourdate",
            constraint=models.UniqueConstraint(fields=("tour", "start_date"), name="unique_tour_start_date"),
        ),
        migrations.AddConstraint(
            model_name="tourdate",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="tourdate_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="tourpricetier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_people__isnull", True),
                    ("max_people__gte", models.F("min_people")),
                    _connector="OR",
                ),
                name="tier_max_gte_min_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="transferroute",
            constraint=models.UniqueConstraint(
                fields=("departure_point", "arrival_point"),
                name="unique_transfer_route_points",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicletype",
            constraint=models.UniqueConstraint(fields=("route", "category"), name="unique_vehicle_category_per_route"),
        ),
    ]
