# Generated by Django 5.2.9 on 2026-06-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0002_remove_sitesettings_tripadvisor_widget_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='name_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='name_es',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='name_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_de',
            field=models.CharField(max_length=64, null=True, verbose_name='Название города'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_es',
            field=models.CharField(max_length=64, null=True, verbose_name='Название города'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_fr',
            field=models.CharField(max_length=64, null=True, verbose_name='Название города'),
        ),
        migrations.AddField(
            model_name='city',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='city',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='city',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_de',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Название страны'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_es',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Название страны'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_fr',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Название страны'),
        ),
        migrations.AddField(
            model_name='country',
            name='hero_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Описание для Hero'),
        ),
        migrations.AddField(
            model_name='country',
            name='hero_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Описание для Hero'),
        ),
        migrations.AddField(
            model_name='country',
            name='hero_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание для Hero'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='price_label_de',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Метка'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='price_label_es',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Метка'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='price_label_fr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Метка'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='title_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='title_es',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='title_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_de',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_de',
            field=models.CharField(max_length=256, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es',
            field=models.CharField(max_length=256, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fr',
            field=models.CharField(max_length=256, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='accommodation_de',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Проживание'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='accommodation_es',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Проживание'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='accommodation_fr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Проживание'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='altitude_de',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='altitude_es',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='altitude_fr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='driving_distance_de',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='На авто'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='driving_distance_es',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='На авто'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='driving_distance_fr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='На авто'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_de',
            field=models.CharField(max_length=256, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_es',
            field=models.CharField(max_length=256, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_fr',
            field=models.CharField(max_length=256, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='walking_distance_de',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Пешком'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='walking_distance_es',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Пешком'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='walking_distance_fr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Пешком'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_de',
            field=models.CharField(max_length=256, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_es',
            field=models.CharField(max_length=256, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_fr',
            field=models.CharField(max_length=256, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_de',
            field=models.TextField(blank=True, null=True, verbose_name='Текст о компании'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_es',
            field=models.TextField(blank=True, null=True, verbose_name='Текст о компании'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Текст о компании'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_de',
            field=models.TextField(blank=True, null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_es',
            field=models.TextField(blank=True, null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_es',
            field=models.CharField(max_length=128, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_es',
            field=models.CharField(max_length=128, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_de',
            field=models.TextField(blank=True, null=True, verbose_name='Включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_es',
            field=models.TextField(blank=True, null=True, verbose_name='Включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_included_de',
            field=models.TextField(blank=True, null=True, verbose_name='Не включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_included_es',
            field=models.TextField(blank=True, null=True, verbose_name='Не включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_included_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Не включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_de',
            field=models.CharField(max_length=256, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_es',
            field=models.CharField(max_length=256, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_fr',
            field=models.CharField(max_length=256, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_de',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_es',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_fr',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='tourroutepoint',
            name='title_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tourroutepoint',
            name='title_es',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tourroutepoint',
            name='title_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='arrival_point_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Куда'),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='arrival_point_es',
            field=models.CharField(max_length=128, null=True, verbose_name='Куда'),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='arrival_point_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Куда'),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='departure_point_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='departure_point_es',
            field=models.CharField(max_length=128, null=True, verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='departure_point_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Откуда'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'city_name_es'), name='unique_city_per_country-city_name_es'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'city_name_fr'), name='unique_city_per_country-city_name_fr'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'city_name_de'), name='unique_city_per_country-city_name_de'),
        ),
        migrations.AddConstraint(
            model_name='transferroute',
            constraint=models.UniqueConstraint(fields=('departure_point', 'arrival_point_es'), name='unique_transfer-arrival_point_es'),
        ),
        migrations.AddConstraint(
            model_name='transferroute',
            constraint=models.UniqueConstraint(fields=('departure_point', 'arrival_point_fr'), name='unique_transfer-arrival_point_fr'),
        ),
        migrations.AddConstraint(
            model_name='transferroute',
            constraint=models.UniqueConstraint(fields=('departure_point', 'arrival_point_de'), name='unique_transfer-arrival_point_de'),
        ),
        migrations.AddConstraint(
            model_name='transferroute',
            constraint=models.UniqueConstraint(fields=('departure_point_es', 'arrival_point'), name='unique_transfer-departure_point_es'),
        ),
        migrations.AddConstraint(
            model_name='transferroute',
            constraint=models.UniqueConstraint(fields=('departure_point_fr', 'arrival_point'), name='unique_transfer-departure_point_fr'),
        ),
        migrations.AddConstraint(
            model_name='transferroute',
            constraint=models.UniqueConstraint(fields=('departure_point_de', 'arrival_point'), name='unique_transfer-departure_point_de'),
        ),
    ]
