# Generated by Django 5.2.9 on 2026-06-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0003_attraction_description_de_attraction_description_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAdvisorManualReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('avatar_url', models.URLField(blank=True, verbose_name='URL аватара')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звёзд')], default=5, verbose_name='Рейтинг')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на оригинальный отзыв')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Ручной отзыв Tripadvisor',
                'verbose_name_plural': 'Ручные отзывы Tripadvisor',
                'ordering': ['order', '-published_date', '-id'],
            },
        ),
    ]
