# Generated by Django 5.2.9 on 2026-05-01 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nomads_area_app",
            "0003_alter_attraction_options_alter_booking_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itineraryday",
            name="description",
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name="tour",
            name="description",
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
    ]
