# Generated by Django 5.2.9 on 2026-05-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0004_alter_itineraryday_description_alter_tour_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer_contact', 'created_at'], name='booking_contact_created_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['phone_or_email', 'created_at'], name='contact_email_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['customer_phone', 'created_at'], name='transport_phone_created_idx'),
        ),
    ]
