# Generated by Django 5.2.9 on 2026-06-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0004_tripadvisormanualreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripAdvisorManualReview',
        ),
    ]
