# Generated by Django 5.2.9 on 2026-06-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomads_area_app", "0005_delete_tripadvisormanualreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="extra_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookings",
                to="nomads_area_app.extraservice",
                verbose_name="Дополнительные услуги",
            ),
        ),
    ]
