# Generated by Django 5.2.9 on 2026-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0005_booking_booking_contact_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tripadvisor_url',
            field=models.URLField(blank=True),
        ),
    ]
