# Generated by Django 5.2.9 on 2026-05-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0006_sitesettings_tripadvisor_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tourdate',
            constraint=models.CheckConstraint(condition=models.Q(('available_spots__lte', 10)), name='tourdate_available_spots_lte_10'),
        ),
    ]
