# Generated by Django 5.2.9 on 2026-06-18 02:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomads_area_app", "0006_booking_extra_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraservice",
            name="features_de",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default=list,
                size=None,
                verbose_name="Фичи (DE)",
            ),
        ),
        migrations.AddField(
            model_name="extraservice",
            name="features_en",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default=list,
                size=None,
                verbose_name="Фичи (EN)",
            ),
        ),
        migrations.AddField(
            model_name="extraservice",
            name="features_es",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default=list,
                size=None,
                verbose_name="Фичи (ES)",
            ),
        ),
        migrations.AddField(
            model_name="extraservice",
            name="features_fr",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default=list,
                size=None,
                verbose_name="Фичи (FR)",
            ),
        ),
        migrations.AddField(
            model_name="extraservice",
            name="features_ru",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default=list,
                size=None,
                verbose_name="Фичи (RU)",
            ),
        ),
    ]
