# Generated by Django 5.2.9 on 2026-05-12 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0007_tourdate_tourdate_available_spots_lte_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='hero_description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='hero_description_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='price_label_en',
            field=models.CharField(default='за 1 день тура', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='price_label_ru',
            field=models.CharField(default='за 1 день тура', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='title_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='accommodation_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='accommodation_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='altitude_en',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='altitude_ru',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_en',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_ru',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='driving_distance_en',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='driving_distance_ru',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='walking_distance_en',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='walking_distance_ru',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='quizansweroption',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizansweroption',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_included_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_included_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tourroutepoint',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tourroutepoint',
            name='title_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='arrival_point_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='arrival_point_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='departure_point_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transferroute',
            name='departure_point_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'city_name_ru'), name='unique_city_per_country-city_name_ru'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'city_name_en'), name='unique_city_per_country-city_name_en'),
        ),
        migrations.AddConstraint(
            model_name='transferroute',
            constraint=models.UniqueConstraint(fields=('departure_point_ru', 'arrival_point'), name='unique_transfer_route_points-departure_point_ru'),
        ),
        migrations.AddConstraint(
            model_name='transferroute',
            constraint=models.UniqueConstraint(fields=('departure_point_en', 'arrival_point'), name='unique_transfer_route_points-departure_point_en'),
        ),
        migrations.AddConstraint(
            model_name='transferroute',
            constraint=models.UniqueConstraint(fields=('departure_point', 'arrival_point_ru'), name='unique_transfer_route_points-arrival_point_ru'),
        ),
        migrations.AddConstraint(
            model_name='transferroute',
            constraint=models.UniqueConstraint(fields=('departure_point', 'arrival_point_en'), name='unique_transfer_route_points-arrival_point_en'),
        ),
    ]
