# Generated by Django 5.2.9 on 2026-05-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0008_attraction_description_en_attraction_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deposit_percent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remainder_amount',
        ),
    ]
