# Generated by Django 5.2.9 on 2026-05-15 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0009_remove_booking_deposit_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('finikpay', 'FinikPay')], default='finikpay', max_length=32)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('external_payment_id', models.CharField(blank=True, default='', max_length=128)),
                ('payment_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменён')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='nomads_area_app.booking')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payment_status_created_idx'), models.Index(fields=['external_payment_id'], name='payment_external_id_idx')],
            },
        ),
    ]
