# Generated by Django 5.2.9 on 2026-05-15 19:38

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0010_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['name'], 'verbose_name': 'Достопримечательность', 'verbose_name_plural': 'Достопримечательности'},
        ),
        migrations.AlterModelOptions(
            name='attractionimage',
            options={'verbose_name': 'Фото достопримечательности', 'verbose_name_plural': 'Фото достопримечательностей'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city_name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Контактная заявка', 'verbose_name_plural': 'Контактные заявки'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='extraservice',
            options={'verbose_name': 'Дополнительная услуга', 'verbose_name_plural': 'Дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='itineraryday',
            options={'ordering': ['day_number'], 'verbose_name': 'День маршрута', 'verbose_name_plural': 'Маршрут по дням'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='quizansweroption',
            options={'ordering': ['order'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='quizlead',
            options={'verbose_name': 'Заявка с квиза', 'verbose_name_plural': 'Заявки с квиза'},
        ),
        migrations.AlterModelOptions(
            name='quizprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Прогресс квиза', 'verbose_name_plural': 'Прогресс квизов'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос квиза', 'verbose_name_plural': 'Вопросы квиза'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория тура', 'verbose_name_plural': 'Категории туров'},
        ),
        migrations.AlterModelOptions(
            name='tourdate',
            options={'ordering': ['start_date'], 'verbose_name': 'Дата заезда', 'verbose_name_plural': 'Даты заезда'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'verbose_name': 'Фото тура', 'verbose_name_plural': 'Фото тура'},
        ),
        migrations.AlterModelOptions(
            name='tourpricetier',
            options={'ordering': ['min_people'], 'verbose_name': 'Цена приватного тура', 'verbose_name_plural': 'Цены приватных туров'},
        ),
        migrations.AlterModelOptions(
            name='tourroutepoint',
            options={'ordering': ['order'], 'verbose_name': 'Точка маршрута', 'verbose_name_plural': 'Точки маршрута'},
        ),
        migrations.AlterModelOptions(
            name='transferroute',
            options={'ordering': ['departure_point', 'arrival_point'], 'verbose_name': 'Маршрут трансфера', 'verbose_name_plural': 'Маршруты трансфера'},
        ),
        migrations.AlterModelOptions(
            name='transportrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на трансфер', 'verbose_name_plural': 'Заявки на трансфер'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['route_id', 'category'], 'verbose_name': 'Тип машины', 'verbose_name_plural': 'Типы машин'},
        ),
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='nomads_area_app.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attractions/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='tours',
            field=models.ManyToManyField(blank=True, related_name='attractions', to='nomads_area_app.tour', verbose_name='Связанные туры'),
        ),
        migrations.AlterField(
            model_name='attractionimage',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nomads_area_app.attraction', verbose_name='Достопримечательность'),
        ),
        migrations.AlterField(
            model_name='attractionimage',
            name='image',
            field=models.ImageField(upload_to='attraction_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Взрослые'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Дети'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_contact',
            field=models.CharField(default='', max_length=128, verbose_name='Контакт клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=128, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.PositiveSmallIntegerField(verbose_name='Количество людей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='people_details',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Состав группы'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Желаемая дата окончания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Желаемая дата начала'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_per_person',
            field=models.PositiveIntegerField(verbose_name='Цена за человека'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='nomads_area_app.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomads_area_app.tourdate', verbose_name='Дата тура'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_image',
            field=models.ImageField(blank=True, null=True, upload_to='city_images/', verbose_name='Изображение города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=64, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='nomads_area_app.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone_or_email',
            field=models.CharField(max_length=128, verbose_name='Телефон или Email'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('answered', 'Отвечено')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_image',
            field=models.ImageField(blank=True, null=True, upload_to='country_images/', verbose_name='Изображение страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='hero_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание для главного блока'),
        ),
        migrations.AlterField(
            model_name='country',
            name='hero_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание для главного блока'),
        ),
        migrations.AlterField(
            model_name='country',
            name='hero_description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание для главного блока'),
        ),
        migrations.AlterField(
            model_name='country',
            name='symbol_image',
            field=models.ImageField(blank=True, null=True, upload_to='country_symbols/', verbose_name='Символ страны'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='extra_services/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='price_label',
            field=models.CharField(default='за 1 день тура', max_length=64, verbose_name='Подпись цены'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='price_label_en',
            field=models.CharField(default='за 1 день тура', max_length=64, null=True, verbose_name='Подпись цены'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='price_label_ru',
            field=models.CharField(default='за 1 день тура', max_length=64, null=True, verbose_name='Подпись цены'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='nomads_area_app.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='nomads_area_app.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='accommodation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Проживание'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='accommodation_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Проживание'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='accommodation_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Проживание'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='altitude',
            field=models.CharField(blank=True, max_length=64, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='altitude_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='altitude_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер дня'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='description_en',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='description_ru',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='driving_distance',
            field=models.CharField(blank=True, max_length=64, verbose_name='Дистанция на машине'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='driving_distance_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Дистанция на машине'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='driving_distance_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Дистанция на машине'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='itinerary/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='nomads_area_app.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='walking_distance',
            field=models.CharField(blank=True, max_length=64, verbose_name='Пешая дистанция'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='walking_distance_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Пешая дистанция'),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='walking_distance_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Пешая дистанция'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='nomads_area_app.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_payment_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='ID платежа во внешней системе'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('finikpay', 'FinikPay')], default='finikpay', max_length=32, verbose_name='Платёжная система'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='quizansweroption',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='quizansweroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='nomads_area_app.quizquestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='quizansweroption',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='quizansweroption',
            name='text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='quizansweroption',
            name='text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='quizlead',
            name='answers',
            field=models.JSONField(verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='quizlead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quizlead',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.AlterField(
            model_name='quizlead',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='quizlead',
            name='phone_or_telegram',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон или Telegram'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='answers',
            field=models.JSONField(default=dict, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='current_question_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Текущий вопрос'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='session_key',
            field=models.CharField(max_length=64, unique=True, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('radio', 'Один ответ'), ('checkbox', 'Несколько ответов'), ('text', 'Текст')], default='radio', max_length=16, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, verbose_name='Текст о компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст о компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст о компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_video_url',
            field=models.URLField(blank=True, verbose_name='Видео о компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_policy_url',
            field=models.URLField(blank=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='routes_count',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='Количество маршрутов'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tourists_count',
            field=models.PositiveIntegerField(default=1200, verbose_name='Количество туристов'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tripadvisor_url',
            field=models.URLField(blank=True, verbose_name='TripAdvisor'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=32, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Лет опыта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, max_length=128, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='activity_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Теги активности'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tours', to='nomads_area_app.tourcategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='nomads_area_app.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='nomads_area_app.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('KGS', 'KGS'), ('USD', 'USD')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description_en',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description_ru',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Лёгкий'), (2, 'Средний'), (3, 'Сложный')], default=2, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность в днях'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='included',
            field=models.TextField(verbose_name='Что включено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='included_en',
            field=models.TextField(null=True, verbose_name='Что включено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='included_ru',
            field=models.TextField(null=True, verbose_name='Что включено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_people',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Максимум людей'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='not_included',
            field=models.TextField(blank=True, verbose_name='Что не включено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='not_included_en',
            field=models.TextField(blank=True, null=True, verbose_name='Что не включено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='not_included_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Что не включено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='season',
            field=models.CharField(choices=[('all_year', 'Круглый год'), ('warm', 'Тёплый сезон'), ('winter', 'Зима')], default='all_year', max_length=16, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Название тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Название тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('group', 'Групповой'), ('private', 'Приватный')], max_length=16, verbose_name='Тип тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tripadvisor_url',
            field=models.URLField(blank=True, null=True, verbose_name='TripAdvisor'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='name_en',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='available_spots',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Доступные места'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='nomads_area_app.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='tour_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nomads_area_app.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourpricetier',
            name='max_people',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимум людей'),
        ),
        migrations.AlterField(
            model_name='tourpricetier',
            name='min_people',
            field=models.PositiveSmallIntegerField(verbose_name='Минимум людей'),
        ),
        migrations.AlterField(
            model_name='tourpricetier',
            name='price_per_person',
            field=models.PositiveIntegerField(verbose_name='Цена за человека'),
        ),
        migrations.AlterField(
            model_name='tourpricetier',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='nomads_area_app.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tourroutepoint',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='tourroutepoint',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='tourroutepoint',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='tourroutepoint',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название точки'),
        ),
        migrations.AlterField(
            model_name='tourroutepoint',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название точки'),
        ),
        migrations.AlterField(
            model_name='tourroutepoint',
            name='title_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название точки'),
        ),
        migrations.AlterField(
            model_name='tourroutepoint',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='nomads_area_app.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='transferroute',
            name='arrival_point',
            field=models.CharField(max_length=128, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='transferroute',
            name='arrival_point_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='transferroute',
            name='arrival_point_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='transferroute',
            name='departure_point',
            field=models.CharField(max_length=128, verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='transferroute',
            name='departure_point_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='transferroute',
            name='departure_point_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='transferroute',
            name='distance_km',
            field=models.PositiveIntegerField(verbose_name='Расстояние, км'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='flight_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Номер рейса'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='luggage_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество багажа'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='passengers',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Пассажиры'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='travel_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поездки'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomads_area_app.vehicletype', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='bags',
            field=models.PositiveSmallIntegerField(verbose_name='Количество мест для багажа'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='category',
            field=models.CharField(choices=[('sedan', 'Седан'), ('minivan', 'Минивэн'), ('minibus', 'Миниавтобус')], max_length=16, verbose_name='Категория машины'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='nomads_area_app.transferroute', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='seats',
            field=models.PositiveSmallIntegerField(verbose_name='Количество мест'),
        ),
    ]
