# Generated by Django 5.2.9 on 2026-05-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0011_alter_attraction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменён'), ('refunded', 'Возврат')], default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
