# Generated by Django 5.2.9 on 2026-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0013_deduplicate_attractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='elfsight_google_reviews_app_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Elfsight Reviews Widget App ID'),
        ),
    ]
