# Generated by Django 5.2.9 on 2026-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0014_alter_sitesettings_elfsight_google_reviews_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_video_url',
            field=models.FileField(blank=True, null=True, upload_to='site/videos/', verbose_name='Видео о компании'),
        ),
    ]
