# Generated by Django 5.2.9 on 2026-06-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0015_alter_sitesettings_about_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_image',
        ),
    ]
