# Generated by Django 5.2.9 on 2026-06-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0016_remove_city_city_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='city',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='city',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='city',
            name='description_ru',
        ),
    ]
