# Generated by Django 5.2.9 on 2026-06-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0017_remove_city_description_remove_city_description_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='image',
        ),
    ]
