# Generated by Django 5.2.9 on 2026-06-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomads_area_app', '0019_sync_itinerary_tags'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['city', 'is_active'], name='attraction_city_active_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['is_active', 'name'], name='attraction_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='booking_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tour', 'status'], name='booking_tour_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tour_date', 'status'], name='booking_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['status', '-created_at'], name='contact_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='extraservice',
            index=models.Index(fields=['tour', 'is_active'], name='extra_service_tour_active_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['tour', 'is_active', 'order'], name='faq_tour_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='quizlead',
            index=models.Index(fields=['status', '-created_at'], name='quiz_lead_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='quizprogress',
            index=models.Index(fields=['updated_at'], name='quiz_progress_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['is_active', 'order'], name='quiz_question_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active', '-created_at'], name='tour_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['country', 'tour_type', 'is_active'], name='tour_country_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['tour', 'start_date'], name='tour_date_tour_start_idx'),
        ),
    ]
